OPEN/account/urls.py
from django.conf.urls import patterns, url

from OPEN.account.views import username_available


urlpatterns = patterns('',

    url(r'^login$', 
	'django.contrib.auth.views.login', 
	{'template_name': 'registration/login.html'},
    ),

    url(r'^logout$', 
	'django.contrib.auth.views.logout', 
	{'next_page': '/accounts/login/'},
    ),

    url(r'^username/available/$',
       username_available,
       name = 'username_available'
    ),



)

OPEN/course/urls.py
from django.conf.urls import patterns, url

from OPEN.course.views import add_comment, add_course, add_new_course, add_forum, add_pdf, add_video, available_course, all_user_courses, course, course_forum_list, course_pdf_list, course_video_list, course_quiz_list, view_file, view_forum, view_video_file


urlpatterns = patterns('',

    url( r'^$', 
        all_user_courses,
        {'template_name': 'course/all_user_courses.html'},
        name = 'all_user_courses' ),

    url( r'^available/$',
        available_course,
        {'template_name': 'course/available_course.html'},
        name = 'available_course' ),
        
    url( r'^(?P<course_id>\d+)/$', 
        course,
        {'template_name': 'course/course.html'},
        name = 'course' ),

    url( r'^(?P<course_id>\d+)/pdf/$', 
        course_pdf_list,
        {'template_name': 'course/course_pdf_list.html'},
        name = 'course_pdf_list' ),

    url( r'^(?P<course_id>\d+)/pdf/(?P<pdf_id>\d+)/$', 
        view_file,
        {'template_name': 'course/view_file.html'},
        name = 'view_file' ),

    url( r'^(?P<course_id>\d+)/video/$', 
        course_video_list,
        {'template_name': 'course/course_video_list.html'},
        name = 'course_video_list' ),

    url( r'^(?P<course_id>\d+)/video/(?P<video_id>\d+)/$', 
        view_video_file,
        {'template_name': 'course/view_video_file.html'},
        name = 'view_video_file' ),

    url( r'^(?P<course_id>\d+)/forum/$', 
        course_forum_list,
        {'template_name': 'course/course_forum_list.html'},
        name = 'course_forum_list' ),

    url( r'^(?P<course_id>\d+)/forum/(?P<forum_id>\d+)/$', 
        view_forum,
        {'template_name': 'course/view_forum.html'},
        name = 'view_forum' ),

    url( r'^(?P<course_id>\d+)/forum/(?P<forum_id>\d+)/comment/$', 
        add_comment,
        name = 'add_comment' ),

    url( r'^(?P<course_id>\d+)/quiz/$', 
        course_quiz_list,
        {'template_name': 'course/course_quiz_list.html'},
        name = 'course_quiz_list' ),

    url(r'^add/$',
       add_course,
       name = 'add_course' ),

    url(r'^(?P<course_id>\d+)/forum/add/$',
       add_forum,
       {'template_name': 'course/add_forum.html'},
       name = 'add_forum' ),

    url(r'^new/$',
       add_new_course,
       {'template_name': 'course/add_course.html'},
       name = 'add_new_course' ),

    url(r'^(?P<course_id>\d+)/video/add/$',
       add_video,
       {'template_name': 'course/add_video.html'},
       name = 'add_video' ),

    url(r'^(?P<course_id>\d+)/pdf/add/$',
       add_pdf,
       {'template_name': 'course/add_pdf.html'},
       name = 'add_pdf' ),
)

OPEN/quiz/urls.py
from django.conf.urls import patterns, url

from OPEN.quiz.views import get_data, instructor_attempt, likert_add, mcquestion_add, openended_add, quiz, quiz_add, quiz_result, user_attempt


urlpatterns = patterns('',

     url( r'^(?P<quiz_id>\d+)/$', 
        quiz,
        {'template_name': 'quiz/quiz.html'},
        name = 'quiz' ),

    url( r'^(?P<quiz_id>\d+)/attempt/$',
        instructor_attempt,
        {'template_name': 'quiz/quiz.html'},
        name = 'instructor_attempt' ),

    url( r'^(?P<quiz_id>\d+)/result/$',
        quiz_result,
        {'template_name': 'quiz/quiz_result.html'},
        name = 'quiz_result' ),

    url( r'^get_data/$',
        get_data,
        name = 'get_data' ),

    url( r'^user_attempt/$',
        user_attempt,
        name = 'user_attempt' ),

    url(r'^(?P<course_id>\d+)/add/$',
       quiz_add,
       {'template_name': 'quiz/quiz_add.html'},
       name = 'quiz_add' ),

    url(r'^(?P<quiz_id>\d+)/mcquestions/$',
       mcquestion_add,
       {'template_name': 'quiz/mcquestion_add.html'},
       name = 'mcquestion_add' ),

    url(r'^(?P<quiz_id>\d+)/likert/$',
       likert_add,
       {'template_name': 'quiz/likert_add.html'},
       name = 'likert_add' ),

    url(r'^(?P<quiz_id>\d+)/openended/$',
       openended_add,
       {'template_name': 'quiz/openended_add.html'},
       name = 'openended_add' ),
)

OPEN/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from OPEN.userprofile.forms import UserProfileForm
from OPEN.userprofile.views import index, registration

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/register/$', registration, {'template_name': 'registration/registration_form.html'}, name='registration_register'),

    url(r'^accounts/', include('registration.backends.simple.urls')),

    url(r'^comments/', include('django.contrib.comments.urls')),

    url( r'^$', index, { 'template_name': 'index.html' }, name = 'index' ),

    url(r'^accounts/', include('OPEN.account.urls')),
    
    url(r'^profile/', include('OPEN.userprofile.urls')),

    url(r'^course/', include('OPEN.course.urls')),

    url(r'^quiz/', include('OPEN.quiz.urls')),

    url(r'^tracking/', include('tracking.urls')),

    url(r'^django-session-idle-timeout/', include('django-session-idle-timeout.urls')),
)

urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', 
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),

    url(r'^adminmedia/(?P<path>.*)$', 'django.views.static.serve', 
        {'document_root': settings.STATIC_ROOT + '/admin', 'show_indexes': True}),
)

handler404 = 'OPEN.account.views.handler404'
handler500 = 'OPEN.account.views.handler500'

OPEN/course/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext as _

from OPEN.base.models import TimeStampAwareModel
from OPEN.institute.models import Institute

from django_countries.fields import CountryField


class Course( TimeStampAwareModel ):
    """
    Course model
    """
    institute = models.ForeignKey(Institute)    
    user = models.ForeignKey(User)

    title = models.CharField(_('title'), max_length = 100)
    description = models.TextField(_('description'), null = True, blank = True)
    code = models.CharField(_('course code'), max_length = 30)
    start_date = models.DateTimeField(_('start date'), blank=True, null=True)
    end_date = models.DateTimeField(_('end date'), blank=True, null=True)

    def __unicode__(self):
        return _("%s") % (self.title)


    class Meta:
        app_label = "course"
        verbose_name = "course"
        verbose_name_plural = "courses"


class Grade( TimeStampAwareModel ):
    """
    Grade model
    """
    GRADE_CHOICES = (
	('', ''),
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
        ('F', 'F'),
    )

    student = models.ForeignKey(User)
    course = models.ForeignKey(Course)
    
    grade = models.CharField(max_length = 2,
                                 choices = GRADE_CHOICES,
                                 blank = True,
                                 null = True,
                                 default = '')

    def __unicode__(self):
        return _("%s_%s") % (self.student, self.course)


    class Meta:
        app_label = "course"
        verbose_name = "student course"
        verbose_name_plural = "student courses"


class UploadedFile( TimeStampAwareModel ):
    """
    Uploaded Files (Video and PDF) model
    """
    FILE_CHOICES = (
        ('', ''),
        ('PDF', 'PDF'),
        ('VID', 'Video'),
            
    )
    
    uploader = models.ForeignKey(User)
    course = models.ForeignKey(Course)

    uploads = models.FileField(blank=True, upload_to='uploaded_files')
    file_type = models.CharField(max_length = 3, 
                                    choices = FILE_CHOICES,
                                    default = '')
    title = models.CharField(_('title'), max_length = 100)
    description = models.TextField(_('description'), null = True, blank = True)

    def __unicode__(self):
        return _("%s") % (self.title)

    class Meta:
        app_label = _("course")
        verbose_name = _("uploaded file")
        verbose_name_plural = _("uploaded files")


class Forum( TimeStampAwareModel ):
    """
    Forums models
    """
    course = models.ForeignKey(Course)
    user = models.ForeignKey(User)
    uploads = models.ForeignKey(UploadedFile)
    
    title = models.CharField(_('title'), max_length = 300)

    def __unicode__(self):
        return _("%s") % (self.title)

    class Meta:
        app_label = _("course")
        verbose_name = _("forum")
        verbose_name_plural = _("forums")

OPEN/quiz/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext as _

from OPEN.base.models import TimeStampAwareModel
from OPEN.course.models import Course, UploadedFile


class Quiz( TimeStampAwareModel ):
    """
    Quiz model
    """
    course = models.ForeignKey(Course)
    user = models.ForeignKey(User)    
    video = models.ForeignKey(UploadedFile)

    title = models.CharField(_('title'), max_length = 100)
    description = models.TextField(_('description'), null = True, blank = True)

    def __unicode__(self):
        return _("%s") % (self.title)

    class Meta:
        app_label = "quiz"
        verbose_name = "quiz"
        verbose_name_plural = "quizzes"


class Question( TimeStampAwareModel ):
    """
    Question model
    Parent for Multiple Choice, Likert Scale and Open Ended questions
    """
    quiz = models.ForeignKey(Quiz)

    content = models.CharField(_('content'), max_length = 1000)
    description = models.TextField(_('description'), null = True, blank = True)    

    def __unicode__(self):
        return _("Question for %s") % (self.quiz.title)

    class Meta:
        app_label = "quiz"
        verbose_name = "question"
        verbose_name_plural = "questions"


class Choice( TimeStampAwareModel ):
    """
    Choice model
    Choices for MCQuestions
    """
    content = models.CharField(_('content'), max_length = 100)

    def __unicode__(self):
        return _("%s") % (self.content)

    class Meta:
        app_label = "quiz"
        verbose_name = "choice"
        verbose_name_plural = "choices"


class MCQuestion( Question ):
    """
    MCQ model
    """
    choice = models.ManyToManyField(Choice)
    
    def __unicode__(self):
        return _("%s") % (self.content)

    class Meta:
        app_label = "quiz"
        verbose_name = "multiple choice question"
        verbose_name_plural = "multiple choice questions"


class MCQAnswer( TimeStampAwareModel ):
    """
    MCQuestion Answer model
    """
    question = models.ForeignKey(MCQuestion)
    correct = models.ForeignKey(Choice)

    def __unicode__(self):
        return _("%s_%s") % (self.question.content, self.question.quiz.video)

    class Meta:
        app_label = "quiz"
        verbose_name = "MCQ answer"
        verbose_name_plural = "MCQ answers"


class Likert( Question ):
    """
    Likert model
    """

    def __unicode__(self):
        return _("%s") % (self.content)

    class Meta:
        app_label = "quiz"
        verbose_name = "likert scale question"
        verbose_name_plural = "likert scale question"


class LikertAnswer( TimeStampAwareModel ):
    """
    Likert Answer model
    """
    SCALE_CHOICES = (
	    ('', ''),
        ('0', '0'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    )
    question = models.ForeignKey(Likert)
    correct = models.CharField(max_length = 2,
                                 choices = SCALE_CHOICES,
                                 blank = True,
                                 null = True,
                                 default = '')

    def __unicode__(self):
        return _("%s, %s") % (self.question.content, self.question.quiz.video)

    class Meta:
        app_label = "quiz"
        verbose_name = "likert answer"
        verbose_name_plural = "likert answers"


class OpenEnded( Question ):
    """
    Open Ended model
    """

    def __unicode__(self):
        return _("%s") % (self.content)

    class Meta:
        app_label = "quiz"
        verbose_name = "open ended question"
        verbose_name_plural = "open ended questions"


class MCQuestionAttempt( TimeStampAwareModel ):
    """
    MCQuestion Attempt model
    """
    answer = models.ForeignKey(Choice)
    mcquestion = models.ForeignKey(MCQuestion)
    student = models.ForeignKey(User)
    
    correct = models.NullBooleanField(blank = True, null = True)
    no_of_attempt = models.PositiveIntegerField(default = 1)
    
    
    def __unicode__(self):
        return _("%s_%s_%s") % (self.student.username, self.mcquestion.quiz, self.no_of_attempt)

    class Meta:
        app_label = "quiz"
        verbose_name = "multiple choice question attempt"
        verbose_name_plural = "multiple choice question attempts"


class LikertAttempt( TimeStampAwareModel ):
    """
    Liket Attempt model
    """
    SCALE_CHOICES = (
	('', ''),
        ('0', '0'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),        
    )

    likert = models.ForeignKey(Likert)
    student = models.ForeignKey(User)

    correct = models.NullBooleanField(blank = True, null = True)
    no_of_attempt = models.PositiveIntegerField(default = 1)    
    scale = models.CharField(max_length = 2,
                                 choices = SCALE_CHOICES,
                                 blank = True,
                                 null = True,
                                 default = '')

    def __unicode__(self):
        return _("%s_%s_%s") % (self.student.username, self.likert.quiz, self.no_of_attempt)

    class Meta:
        app_label = "quiz"
        verbose_name = "likert scale attempt"
        verbose_name_plural = "likert scale attempts"


class OpenEndedAttempt( TimeStampAwareModel ):
    """
    Open Ended Attempt model
    """
    openended = models.ForeignKey(OpenEnded)
    student = models.ForeignKey(User)
    
    answer = models.TextField(_('answer'), null = True, blank = True)        
    no_of_attempt = models.PositiveIntegerField(default = 1)    
  
    def __unicode__(self):
        return _("%s_%s_%s") % (self.student.get_full_name(), self.openended.quiz, self.no_of_attempt)

    class Meta:
        app_label = "quiz"
        verbose_name = "open ended attempt"
        verbose_name_plural = "open ended attempts"

OPEN/quiz/forms.py
from django.forms import ModelForm, Textarea, TextInput

from OPEN.quiz.models import Quiz


class AddQuizForm(ModelForm):
    """
    Add new Quiz
    """
    class Meta:
        model = Quiz
        exclude = ['date_deleted', 'course', 'user']
        widgets = {
            'title': TextInput(attrs={'placeholder': 'Title'}),
            'description': Textarea(attrs={'placeholder': 'Quiz Description', 'rows': 4}),
        }

OPEN/userprofile/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm, PasswordInput, TextInput
from OPEN.userprofile.models import UserProfile


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'first_name', 'last_name')
        widgets = {
            'password': PasswordInput(attrs={'placeholder': 'Password'}),
            'username': TextInput(attrs={'placeholder': 'Username'}),
            'email': TextInput(attrs={'placeholder': 'Email'}),
            'first_name': TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': TextInput(attrs={'placeholder': 'Last Name'}),    
        }

        
class UserProfileForm( ModelForm ):
    class Meta:
        model = UserProfile
        fields = ['avatar', 'address', 'country', 'city', 'phone', 'date_of_birth', 'website']
        widgets = {
            'address': TextInput(attrs={'placeholder': 'Address'}),
            'city': TextInput(attrs={'placeholder': 'City'}),
            'phone': TextInput(attrs={'placeholder': 'Phone'}),
            'date_of_birth': TextInput(attrs={'placeholder': 'Date of Birth'}),
            'website': TextInput(attrs={'placeholder': 'Web Site'}),
        }

OPEN/account/views.py
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.utils import simplejson
from django.views.decorators.csrf import csrf_exempt

from annoying.decorators import ajax_request


@ajax_request
@csrf_exempt
def username_available(request):
    """
    Check username availability for new user
    """
    if request.is_ajax():
        if request.method == 'POST':
            username = request.POST.get('username', '')            
            try:
                user = User.objects.get(username = username)
            except User.DoesNotExist:
                return HttpResponse(simplejson.dumps('True'), mimetype = 'application/json' )
            return HttpResponse(simplejson.dumps('False'), mimetype = 'application/json' )            
    return HttpResponseRedirect('/')

def handler404(request):
    return render(request, '404.html')

def handler500(request):
    return render(request, '500.html')

OPEN/institute/views.py
from django.shortcuts import render

# Create your views here.

OPEN/templates/quiz/likert_add.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans "Add New Likert Questions" %}
{% endblock %}

{% block content %}
<div class="avatar alpha pull-left" onmouseover="show.style.display = 'block';", onmouseout="show.style.display = 'none';">
	    <img src="{{ STATIC_URL }}img/quiz.jpg" />
        </div>
<div class="span6 profileRows">
	<h2 class="profileHeading">Likert Questions</h2>
    {% if form.errors %}
        <p class="error">Please correct the errors below: {{ form.non_field_errors }}</p>
    {% endif %}

  <div class="span5" id="regForm">
  <form enctype="multipart/form-data" method="POST" action="{% url 'likert_add' quiz_id %}" class="form-horizontal" name="AddQuestionForm">
	{% csrf_token %}
    <div id="qs_list">
      {% for c in counter %}
      <div class="control-group">
          <label class="control-label" for="id_content_{{ c }}"><strong>Qs. {{ c }}</strong></label>
          <div class="controls">
              <input type="text" placeholder="Likert Question" name="content_{{ c }}" class="qs-input" maxlength="1000" id="id_content_{{ c }}">
              {% if form.title.errors %}
                <p class="error">{{ form.title.errors.as_text }}</p>
            {% endif %}
          </div>
          <div class="span5" style="margin-left:100px;"><hr></div>
    </div>
    {% endfor %}
    </div>
      {% if qs_bank %}
          <div class="control-group" style="margin-left:100px;">
          <select multiple="multiple" name="bank" id="bank" size="10" style="width:500px;">
              {% for qs in qs_bank %}
                <option value="{{ qs.id }}">{{ qs }}</option>
              {% endfor %}
          </select>
          <p class="smallText">Press CTRL to select multiple questions</p>
          </div>
      {% endif %}
    <div class="control-group">
	<div class="controls">
        <button id="add_more" class="btn">Add More Qs.</button>
		<button type="submit" class="btn">Submit</button>
	</div>
    </div>
  </form>
  </div>
</div>

{% endblock %}

{% block extra_body %}
<script type="text/javascript">
	$('#add_more').click(function(event){
	    event.preventDefault();
	    var count = $('#qs_list').children().length + 1;
        qs_list = "<div class=\"control-group\"><label class=\"control-label\" for=\"id_content_" + count + "\"><strong>Qs. " + count + "</strong></label><div class=\"controls\"><input type=\"text\" placeholder=\"Likert Question\" name=\"content_" + count + "\" class=\"qs-input\" maxlength=\"1000\" id=\"id_content_" + count + "\"><p class=\"error\"></p></div><div class=\"span5\" style=\"margin-left:100px;\"><hr></div></div>";
        $('#qs_list').append(qs_list);
	});
</script>
{% endblock %}

OPEN/templates/quiz/openended_add.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans "Add New Open-Ended Questions" %}
{% endblock %}

{% block content %}
<div class="avatar alpha pull-left" onmouseover="show.style.display = 'block';", onmouseout="show.style.display = 'none';">
	    <img src="{{ STATIC_URL }}img/quiz.jpg" />
        </div>
<div class="span6 profileRows">
	<h2 class="profileHeading">OpenEnded Questions</h2>
    {% if form.errors %}
        <p class="error">Please correct the errors below: {{ form.non_field_errors }}</p>
    {% endif %}

  <div class="span5" id="regForm">
  <form enctype="multipart/form-data" method="POST" action="{% url 'openended_add' quiz_id %}" class="form-horizontal" name="AddQuestionForm">
	{% csrf_token %}
    <div id="qs_list">
      {% for c in counter %}
      <div class="control-group">
          <label class="control-label" for="id_content_{{ c }}"><strong>Qs. {{ c }}</strong></label>
          <div class="controls">
              <input type="text" placeholder="Open-Ended Question" name="content_{{ c }}" class="qs-input" maxlength="1000" id="id_content_{{ c }}">
              {% if form.title.errors %}
                <p class="error">{{ form.title.errors.as_text }}</p>
            {% endif %}
          </div>
          <div class="span5" style="margin-left:100px;"><hr></div>
    </div>
    {% endfor %}
    </div>
    <div class="control-group">
	<div class="controls">
        <button id="add_more" class="btn">Add More Qs.</button>
		<button type="submit" class="btn">Submit</button>
	</div>
    </div>
  </form>
  </div>
</div>

{% endblock %}

{% block extra_body %}
<script type="text/javascript">
	$('#add_more').click(function(event){
	    event.preventDefault();
	    var count = $('#qs_list').children().length + 1;
        qs_list = "<div class=\"control-group\"><label class=\"control-label\" for=\"id_content_" + count + "\"><strong>Qs. " + count + "</strong></label><div class=\"controls\"><input type=\"text\" placeholder=\"Open-Ended Question\" name=\"content_" + count + "\" class=\"qs-input\" maxlength=\"1000\" id=\"id_content_" + count + "\"><p class=\"error\"></p></div><div class=\"span5\" style=\"margin-left:100px;\"><hr></div></div>";
        $('#qs_list').append(qs_list);
	});
</script>
{% endblock %}

OPEN/templates/quiz/quiz_add.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans "Add New Quiz" %}
{% endblock %}

{% block content %}
<div class="avatar alpha pull-left" onmouseover="show.style.display = 'block';", onmouseout="show.style.display = 'none';">
	    <img src="{{ STATIC_URL }}img/quiz.jpg" />
        </div>
<div class="span6 profileRows">
	<h2 class="profileHeading">Add New Quiz<span class="pull-right"><a href="{% url 'course_quiz_list' course_id %}" class="Edit">Back<i class="icon-arrow-left"></i></a></span></h2>
    {% if form.errors %}
        <p class="error">Please correct the errors below: {{ form.non_field_errors }}</p>
    {% endif %}

  <div class="span5" id="regForm">
  <form enctype="multipart/form-data" method="POST" action="{% url 'quiz_add' course_id %}" class="form-horizontal" name="AddQuizForm">
	{% csrf_token %}
      <div class="control-group" style="margin-top:30px;">
      <label class="control-label" for="id_title">Title</label>
      <div class="controls">
	      {{ form.title }}
	      {% if form.title.errors %}
        <p class="error">{{ form.title.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

      <div class="control-group" style="margin-top:30px;">
      <label class="control-label" for="id_video">Video</label>
      <div class="controls">
	      {{ form.video }}
	      {% if form.video.errors %}
        <p class="error">{{ form.video.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

      <div class="control-group" style="margin-top:30px;">
      <label class="control-label" for="id_description">Description</label>
      <div class="controls">
	      {{ form.description }}
	      {% if form.description.errors %}
        <p class="error">{{ form.description.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

    <div class="control-group">
	<div class="controls">
		<button type="submit" class="btn">Next</button>
	</div>
    </div>
  </form>
  </div>
</div>

{% endblock %}