OPEN/account/urls.py
from django.conf.urls import patterns, url

from OPEN.account.views import username_available


urlpatterns = patterns('',

    url(r'^login$', 
	'django.contrib.auth.views.login', 
	{'template_name': 'registration/login.html'},
    ),

    url(r'^logout$', 
	'django.contrib.auth.views.logout', 
	{'next_page': '/accounts/login/'},
    ),

    url(r'^username/available/$',
       username_available,
       name = 'username_available'
    ),



)

OPEN/course/urls.py
from django.conf.urls import patterns, url

from OPEN.course.views import add_comment, add_course, add_new_course, add_forum, add_pdf, add_video, available_course, all_user_courses, course, course_forum_list, course_pdf_list, course_video_list, course_quiz_list, view_file, view_forum, view_video_file


urlpatterns = patterns('',

    url( r'^$', 
        all_user_courses,
        {'template_name': 'course/all_user_courses.html'},
        name = 'all_user_courses' ),

    url( r'^available/$',
        available_course,
        {'template_name': 'course/available_course.html'},
        name = 'available_course' ),
        
    url( r'^(?P<course_id>\d+)/$', 
        course,
        {'template_name': 'course/course.html'},
        name = 'course' ),

    url( r'^(?P<course_id>\d+)/pdf/$', 
        course_pdf_list,
        {'template_name': 'course/course_pdf_list.html'},
        name = 'course_pdf_list' ),

    url( r'^(?P<course_id>\d+)/pdf/(?P<pdf_id>\d+)/$', 
        view_file,
        {'template_name': 'course/view_file.html'},
        name = 'view_file' ),

    url( r'^(?P<course_id>\d+)/video/$', 
        course_video_list,
        {'template_name': 'course/course_video_list.html'},
        name = 'course_video_list' ),

    url( r'^(?P<course_id>\d+)/video/(?P<video_id>\d+)/$', 
        view_video_file,
        {'template_name': 'course/view_video_file.html'},
        name = 'view_video_file' ),

    url( r'^(?P<course_id>\d+)/forum/$', 
        course_forum_list,
        {'template_name': 'course/course_forum_list.html'},
        name = 'course_forum_list' ),

    url( r'^(?P<course_id>\d+)/forum/(?P<forum_id>\d+)/$', 
        view_forum,
        {'template_name': 'course/view_forum.html'},
        name = 'view_forum' ),

    url( r'^(?P<course_id>\d+)/forum/(?P<forum_id>\d+)/comment/$', 
        add_comment,
        name = 'add_comment' ),

    url( r'^(?P<course_id>\d+)/quiz/$', 
        course_quiz_list,
        {'template_name': 'course/course_quiz_list.html'},
        name = 'course_quiz_list' ),

    url(r'^add/$',
       add_course,
       name = 'add_course' ),

    url(r'^(?P<course_id>\d+)/forum/add/$',
       add_forum,
       {'template_name': 'course/add_forum.html'},
       name = 'add_forum' ),

    url(r'^new/$',
       add_new_course,
       {'template_name': 'course/add_course.html'},
       name = 'add_new_course' ),

    url(r'^(?P<course_id>\d+)/video/add/$',
       add_video,
       {'template_name': 'course/add_video.html'},
       name = 'add_video' ),

    url(r'^(?P<course_id>\d+)/pdf/add/$',
       add_pdf,
       {'template_name': 'course/add_pdf.html'},
       name = 'add_pdf' ),
)

OPEN/quiz/urls.py
from django.conf.urls import patterns, url

from OPEN.quiz.views import get_data, instructor_attempt, likert_add, mcquestion_add, openended_add, quiz, quiz_add, quiz_result, user_attempt


urlpatterns = patterns('',

     url( r'^(?P<quiz_id>\d+)/$', 
        quiz,
        {'template_name': 'quiz/quiz.html'},
        name = 'quiz' ),

    url( r'^(?P<quiz_id>\d+)/attempt/$',
        instructor_attempt,
        {'template_name': 'quiz/quiz.html'},
        name = 'instructor_attempt' ),

    url( r'^(?P<quiz_id>\d+)/result/$',
        quiz_result,
        {'template_name': 'quiz/quiz_result.html'},
        name = 'quiz_result' ),

    url( r'^get_data/$',
        get_data,
        name = 'get_data' ),

    url( r'^user_attempt/$',
        user_attempt,
        name = 'user_attempt' ),

    url(r'^(?P<course_id>\d+)/add/$',
       quiz_add,
       {'template_name': 'quiz/quiz_add.html'},
       name = 'quiz_add' ),

    url(r'^(?P<quiz_id>\d+)/mcquestions/$',
       mcquestion_add,
       {'template_name': 'quiz/mcquestion_add.html'},
       name = 'mcquestion_add' ),

    url(r'^(?P<quiz_id>\d+)/likert/$',
       likert_add,
       {'template_name': 'quiz/likert_add.html'},
       name = 'likert_add' ),

    url(r'^(?P<quiz_id>\d+)/openended/$',
       openended_add,
       {'template_name': 'quiz/openended_add.html'},
       name = 'openended_add' ),
)

OPEN/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from OPEN.userprofile.forms import UserProfileForm
from OPEN.userprofile.views import index, registration

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/register/$', registration, {'template_name': 'registration/registration_form.html'}, name='registration_register'),

    url(r'^accounts/', include('registration.backends.simple.urls')),

    url(r'^comments/', include('django.contrib.comments.urls')),

    url( r'^$', index, { 'template_name': 'index.html' }, name = 'index' ),

    url(r'^accounts/', include('OPEN.account.urls')),
    
    url(r'^profile/', include('OPEN.userprofile.urls')),

    url(r'^course/', include('OPEN.course.urls')),

    url(r'^quiz/', include('OPEN.quiz.urls')),

    url(r'^tracking/', include('tracking.urls')),

    url(r'^django-session-idle-timeout/', include('django-session-idle-timeout.urls')),
)

urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', 
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),

    url(r'^adminmedia/(?P<path>.*)$', 'django.views.static.serve', 
        {'document_root': settings.STATIC_ROOT + '/admin', 'show_indexes': True}),
)

handler404 = 'OPEN.account.views.handler404'
handler500 = 'OPEN.account.views.handler500'

OPEN/account/models.py
from django.db import models

# Create your models here.

OPEN/course/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext as _

from OPEN.base.models import TimeStampAwareModel
from OPEN.institute.models import Institute

from django_countries.fields import CountryField


class Course( TimeStampAwareModel ):
    """
    Course model
    """
    institute = models.ForeignKey(Institute)    
    user = models.ForeignKey(User)

    title = models.CharField(_('title'), max_length = 100)
    description = models.TextField(_('description'), null = True, blank = True)
    code = models.CharField(_('course code'), max_length = 30)
    start_date = models.DateTimeField(_('start date'), blank=True, null=True)
    end_date = models.DateTimeField(_('end date'), blank=True, null=True)

    def __unicode__(self):
        return _("%s") % (self.title)


    class Meta:
        app_label = "course"
        verbose_name = "course"
        verbose_name_plural = "courses"


class Grade( TimeStampAwareModel ):
    """
    Grade model
    """
    GRADE_CHOICES = (
	('', ''),
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
        ('F', 'F'),
    )

    student = models.ForeignKey(User)
    course = models.ForeignKey(Course)
    
    grade = models.CharField(max_length = 2,
                                 choices = GRADE_CHOICES,
                                 blank = True,
                                 null = True,
                                 default = '')

    def __unicode__(self):
        return _("%s_%s") % (self.student, self.course)


    class Meta:
        app_label = "course"
        verbose_name = "student course"
        verbose_name_plural = "student courses"


class UploadedFile( TimeStampAwareModel ):
    """
    Uploaded Files (Video and PDF) model
    """
    FILE_CHOICES = (
        ('', ''),
        ('PDF', 'PDF'),
        ('VID', 'Video'),
            
    )
    
    uploader = models.ForeignKey(User)
    course = models.ForeignKey(Course)

    uploads = models.FileField(blank=True, upload_to='uploaded_files')
    file_type = models.CharField(max_length = 3, 
                                    choices = FILE_CHOICES,
                                    default = '')
    title = models.CharField(_('title'), max_length = 100)
    description = models.TextField(_('description'), null = True, blank = True)

    def __unicode__(self):
        return _("%s") % (self.title)

    class Meta:
        app_label = _("course")
        verbose_name = _("uploaded file")
        verbose_name_plural = _("uploaded files")


class Forum( TimeStampAwareModel ):
    """
    Forums models
    """
    course = models.ForeignKey(Course)
    user = models.ForeignKey(User)
    uploads = models.ForeignKey(UploadedFile)
    
    title = models.CharField(_('title'), max_length = 300)

    def __unicode__(self):
        return _("%s") % (self.title)

    class Meta:
        app_label = _("course")
        verbose_name = _("forum")
        verbose_name_plural = _("forums")

OPEN/course/forms.py
from django.forms import CharField, DateInput, FileField, Form, ModelForm, Textarea, TextInput, ValidationError

from OPEN.course.models import Course, Forum


class AddForumForm(Form):
    """
    Add new Forum
    """
    title = CharField(max_length=100)
    uploads = FileField(required = True)

    def clean_uploads(self):
        uploads = self.cleaned_data['uploads']
        ext = uploads.name.split('.')[-1]
        if ext == 'pdf' or ext == 'webm':
            return uploads
        else:
            raise ValidationError("Not a valid upload file")


class AddCourseForm(ModelForm):
    """
    Add new Course
    """
    class Meta:
        model = Course
        exclude = ['date_deleted', 'user']
        widgets = {
            'title': TextInput(attrs={'placeholder': 'Title'}),
            'code': TextInput(attrs={'placeholder': 'Course Code'}),
            'description': Textarea(attrs={'placeholder': 'Course Description', 'rows': 4}),
            'start_date': DateInput(attrs={'placeholder': 'YYYY-MM-DD'}),
            'end_date': DateInput(attrs={'placeholder': 'YYYY-MM-DD'}),
        }


class AddVideoForm(Form):
    """
    Add new Video
    """
    title = CharField(max_length=100)
    uploads = FileField(required = True)

    def clean_uploads(self):
        uploads = self.cleaned_data['uploads']
        ext = uploads.name.split('.')[-1]
        if ext == 'webm':
            return uploads
        else:
            raise ValidationError("Not a valid video file. Only .webm is accepted")


class AddPdfForm(Form):
    """
    Add new Video
    """
    title = CharField(max_length=100)
    uploads = FileField(required = True)

    def clean_uploads(self):
        uploads = self.cleaned_data['uploads']
        ext = uploads.name.split('.')[-1]
        if ext == 'pdf':
            return uploads
        else:
            raise ValidationError("Not a valid pdf file")

OPEN/account/views.py
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.utils import simplejson
from django.views.decorators.csrf import csrf_exempt

from annoying.decorators import ajax_request


@ajax_request
@csrf_exempt
def username_available(request):
    """
    Check username availability for new user
    """
    if request.is_ajax():
        if request.method == 'POST':
            username = request.POST.get('username', '')            
            try:
                user = User.objects.get(username = username)
            except User.DoesNotExist:
                return HttpResponse(simplejson.dumps('True'), mimetype = 'application/json' )
            return HttpResponse(simplejson.dumps('False'), mimetype = 'application/json' )            
    return HttpResponseRedirect('/')

def handler404(request):
    return render(request, '404.html')

def handler500(request):
    return render(request, '500.html')

OPEN/institute/views.py
from django.shortcuts import render

# Create your views here.

OPEN/userprofile/views.py
from datetime import datetime
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, render_to_response
from django.template import RequestContext

from OPEN.course.models import Grade
from OPEN.userprofile.forms import UserForm, UserProfileForm
from OPEN.userprofile.models import UserProfile
from OPEN.quiz.models import MCQuestionAttempt


def index (request, template_name):
    """
    Landing page for anonymous user
    Sign in and Sign up functionality handled
    """
    if request.user.is_authenticated():
        try:
            userprofile = UserProfile.objects.get(user = request.user)
        except UserProfile.DoesNotExist:
            return HttpResponseRedirect(reverse('registration_register'))
        grades = Grade.objects.filter(student = userprofile.user, course__start_date__lte = datetime.now()).order_by('-date_added')
        try:
            course_id = MCQuestionAttempt.objects.filter(student = request.user)[0].mcquestion.quiz.course.id
        except IndexError:
            course_id = None
        return render_to_response('userprofile/profile.html', context_instance=RequestContext(request, {'userprofile': userprofile, 'grades': grades, 'course': course_id}))
    else: 
        if request.POST:
            form_type = request.POST['form']
            if form_type == 'form1':
                username = request.POST['username']
                password = request.POST['password']
                user = authenticate(username=username, password=password)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        try:
                            userprofile = UserProfile.objects.get(user = user)
                        except UserProfile.DoesNotExist:
                            return HttpResponseRedirect(reverse('registration_register'))
                        grades = Grade.objects.filter(student = userprofile.user, course__start_date__lte = datetime.now()).order_by('-date_added')
                        return render_to_response('userprofile/profile.html', context_instance=RequestContext(request, {'userprofile': userprofile, 'grades': grades}))
                else:
                    form = AuthenticationForm(None, request.POST)
                    return render_to_response('registration/login.html', context_instance=RequestContext(request, {'form': form}))
            if form_type == 'form2':
                form = UserForm(request.POST)
                if form.is_valid():
                    user = User.objects.create_user(**form.cleaned_data)
                    new_user = authenticate(username=request.POST['username'], 
                                            password=request.POST['password'])
                    login(request, new_user)
                return HttpResponseRedirect(reverse('registration_register'))
        else:
            form = UserForm()
            return render_to_response(template_name, context_instance=RequestContext(request, {'form': form}))
    return HttpResponseRedirect(reverse('registration_register'))
    
@login_required
def registration (request, template_name):
    """
    Show, Create and Edit users profile
    """
    try:
        userprofile = request.user.get_profile()
    except UserProfile.DoesNotExist:
        userprofile = {}

    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            if userprofile:
                if request.FILES and request.FILES['avatar'] is not None:
                    userprofile.avatar = request.FILES['avatar']
                userprofile.address = request.POST['address']
                userprofile.country = request.POST['country']
                userprofile.city = request.POST['city']
                userprofile.phone = request.POST['phone']
                if request.POST['date_of_birth']:
                    userprofile.date_of_birth = request.POST['date_of_birth']
                userprofile.website = request.POST['website']
                userprofile.save()
            else:
                obj = form.save(commit = False)
                obj.user = request.user
                obj.save()
            grades = Grade.objects.filter(student = request.user, course__start_date__lte = datetime.now()).order_by('-date_added')
            return render_to_response('userprofile/profile.html', context_instance=RequestContext(request, {'userprofile': userprofile, 'grades': grades}))
        else:
            return render_to_response(template_name, context_instance=RequestContext(request, {'form': form}))
    else:
        if userprofile:
            data = {
                "avatar": userprofile.avatar,
                "address": userprofile.address, 
                "country": userprofile.country,
                "city": userprofile.city,
                "phone": userprofile.phone,
                "date_of_birth": userprofile.date_of_birth,
                "website": userprofile.website,
            }
            form = UserProfileForm(data)
        else:
            form = UserProfileForm()
            
        return render_to_response(template_name, context_instance=RequestContext(request, {'form': form}))

OPEN/templates/course/add_course.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans "Add New Course" %}
{% endblock %}

{% block content %}
<div class="avatar alpha pull-left" onmouseover="show.style.display = 'block';", onmouseout="show.style.display = 'none';">
	    <img src="{{ STATIC_URL }}img/course.jpg" />
        </div>
<div class="span6 profileRows">
	<h2 class="profileHeading">Add New Course<span class="pull-right"><a href="{% url 'all_user_courses' %}" class="Edit"><i class="icon-arrow-left"></i> Back</a></span></h2>
    {% if form.errors %}
        <p class="error">Please correct the errors below: {{ form.non_field_errors }}</p>
    {% endif %}

  <div class="span5" id="regForm">
  <form enctype="multipart/form-data" method="POST" action="{% url 'add_new_course' %}" class="form-horizontal" name="AddCourseForm">
	{% csrf_token %}
      <div class="control-group mt10">
      <label class="control-label" for="id_title">Title</label>
      <div class="controls">
	      {{ form.title }}
	      {% if form.title.errors %}
        <p class="error">{{ form.title.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

      <div class="control-group">
      <label class="control-label" for="id_institute">Institute</label>
      <div class="controls">
	      {{ form.institute }}
	      {% if form.institute.errors %}
        <p class="error">{{ form.institute.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

            <div class="control-group">
      <label class="control-label" for="id_code">Course Code</label>
      <div class="controls">
	      {{ form.code }}
	      {% if form.code.errors %}
        <p class="error">{{ form.code.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

            <div class="control-group">
      <label class="control-label" for="id_start_date">Starting Date</label>
      <div class="controls">
	      {{ form.start_date }}
	      {% if form.start_date.errors %}
        <p class="error">{{ form.start_date.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

            <div class="control-group">
      <label class="control-label" for="id_end_date">Ending Date</label>
      <div class="controls">
	      {{ form.end_date }}
	      {% if form.end_date.errors %}
        <p class="error">{{ form.end_date.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

      <div class="control-group">
      <label class="control-label" for="id_description">Description</label>
      <div class="controls">
	      {{ form.description }}
	      {% if form.description.errors %}
        <p class="error">{{ form.description.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

    <div class="control-group">
	<div class="controls">
		<button type="submit" class="btn">Done</button>
	</div>
    </div>
  </form>
  </div>
</div>

{% endblock %}

OPEN/templates/course/add_forum.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans "Add New Forum" %}
{% endblock %}

{% block content %}

 <h2>Add new forum for {{ course }} </h2>

 {% if form.errors %}
  <p class="error">Please correct the errors below: {{ form.non_field_errors }}</p>
 {% endif %}

  <div class="span5" id="regForm">
  <form enctype="multipart/form-data" method="POST" action="{% url 'add_forum' course_id %}" class="form-horizontal" name="AddForumForm">
	{% csrf_token %}

      <div class="control-group" style="margin-top:30px;">
      <label class="control-label" for="id_title">Forum Title</label>
      <div class="controls">
	      {{ form.title }}
	      {% if form.title.errors %}
        <p class="error">{{ form.title.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

      <div class="control-group" style="margin-top:40px;">
      <label class="control-label" for="id_uploads">Select File</label>
      <div class="controls">
	      {{ form.uploads }}
	      {% if form.uploads.errors %}
        <p class="error">{{ form.uploads.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

       <input type="hidden" id="id_course" name="course" value={{ course_id }}>

    <div class="control-group">
	<div class="controls">
		<button type="submit" class="btn">Done</button>
	</div>
    </div>
  </form>
  </div>

{% endblock %}

OPEN/templates/course/add_pdf.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans "Add New PDF" %}
{% endblock %}

{% block content %}

 <h2>Add new PDF for {{ course }} </h2>

 {% if form.errors %}
  <p class="error">Please correct the errors below: {{ form.non_field_errors }}</p>
 {% endif %}

  <div class="span5" id="regForm">
  <form enctype="multipart/form-data" method="POST" action="{% url 'add_pdf' course_id %}" class="form-horizontal" name="AddPdfForm">
	{% csrf_token %}

      <div class="control-group" style="margin-top:30px;">
      <label class="control-label" for="id_title">PDF Title</label>
      <div class="controls">
	      {{ form.title }}
	      {% if form.title.errors %}
        <p class="error">{{ form.title.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

      <div class="control-group" style="margin-top:40px;">
      <label class="control-label" for="id_uploads">Select File</label>
      <div class="controls">
	      {{ form.uploads }}
	      {% if form.uploads.errors %}
        <p class="error">{{ form.uploads.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

       <input type="hidden" id="id_course" name="course" value={{ course_id }}>

    <div class="control-group">
	<div class="controls">
		<button type="submit" class="btn">Done</button>
	</div>
    </div>
  </form>
  </div>

{% endblock %}

OPEN/templates/course/add_video.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans "Add New Video" %}
{% endblock %}

{% block content %}

 <h2>Add new video for {{ course }} </h2>

 {% if form.errors %}
  <p class="error">Please correct the errors below: {{ form.non_field_errors }}</p>
 {% endif %}

  <div class="span5" id="regForm">
  <form enctype="multipart/form-data" method="POST" action="{% url 'add_video' course_id %}" class="form-horizontal" name="AddVideoForm">
	{% csrf_token %}

      <div class="control-group" style="margin-top:30px;">
      <label class="control-label" for="id_title">Video Title</label>
      <div class="controls">
	      {{ form.title }}
	      {% if form.title.errors %}
        <p class="error">{{ form.title.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

      <div class="control-group" style="margin-top:40px;">
      <label class="control-label" for="id_uploads">Select File</label>
      <div class="controls">
	      {{ form.uploads }}
	      {% if form.uploads.errors %}
        <p class="error">{{ form.uploads.errors.as_text }}</p>
      {% endif %}
      </div>
    </div>

       <input type="hidden" id="id_course" name="course" value={{ course_id }}>

    <div class="control-group">
	<div class="controls">
		<button type="submit" class="btn">Done</button>
	</div>
    </div>
  </form>
  </div>

{% endblock %}

OPEN/templates/course/all_user_courses.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans "My Courses" %}
{% endblock %}

{% block content %}
<div class="avatar alpha pull-left" onmouseover="show.style.display = 'block';", onmouseout="show.style.display = 'none';">
	    <img src="{{ STATIC_URL }}img/course.jpg" />
        </div>
<div class="span6 profileRows">
	<h2 class="profileHeading">My Courses<span class="pull-right">
        {% ifequal request.user.get_profile.role 'in' %}
            <a href="{% url 'add_new_course' %}" class="Edit"><i class="icon-plus"></i> Add</a>
        {% else %}
            <a href="{% url 'available_course' %}" class="Edit"><i class="icon-plus"></i> Add</a>
        {% endifequal %}

    </span></h2>
	{% if grades %} 	
        <ul>
	{% for grade in grades %}
            <li class="clearfix">
            <div class="span5 pull-left alpha">
		    <a href="{% url 'course' grade.course.id %}"><p><strong>{{ grade.course.title }}</strong></p></a>
		    <p class="smallText">{{ grade.course.description }}</p>
            </div>            
            </li>
	    <hr>
	{% endfor %}
          </ul>  
	  {% else %}
	<p class="smallText">You have no course added to your list. Click on the Add button to select a course.</p>
	  {% endif %}
	<div style="clear:both;"></div> 
	</div>

{% endblock %}

OPEN/templates/course/available_course.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans "Available Courses" %}
{% endblock %}

{% block content %}
	 <div class="avatar alpha pull-left" onmouseover="show.style.display = 'block';", onmouseout="show.style.display = 'none';">
	    <img src="{{ STATIC_URL }}img/course.jpg" />
        </div>
	
<div class="span6 profileRows">
	<h2 class="profileHeading">Add Courses</h2>
        	
        <ul id="top">
	{% if courses %}
	{% for course in courses %}
	    {% csrf_token %}
	    <li class="clearfix course" id="course_{{ course.id }}">
            <div class="span5 pull-left alpha">
		    <div class="span4 ml0">
		    	<a href="{% url 'course' course.id %}"><p><strong>{{ course.title }}</strong></p></a>
		    </div>
		    <div class="span1 addCourse" id="{{ course.id }}">
		    	<i class="icon-ok"></i>
		    </div>
		    <div style="clear:both;"></div> 		    
		    <p class="smallText">{{ course.description }}</p>
            </div>            
	    <div style="clear:both;"></div> 
	    <hr>	    
            </li>
	{% endfor %}
	{% else %}
	<p class="smallText">No new available courses</p>		
	{% endif %}
          </ul>  
 	
	<div style="clear:both;"></div> 
	</div>

{% endblock %}

{% block extra_body %}
<script type="text/javascript">

$('.addCourse').click(function(e) {
	var flag = confirm("Do you want to proceed with adding this course?")
	if (flag){
	$.ajax({
        url : "{% url 'add_course' %}",
        type: "POST",
        data : {csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value,
	               course_id: $(this).attr('id'),
               },
        dataType : "json",
        success: function( response ){
            console.log($("#course_"+response['course_id']));
            if(response['status']){
	    	$("#course_"+response['course_id']).hide("slow");
            }
	    count = $(".course").size() - $(".course").filter(":hidden").size();
	    if(count <= 1){
		document.getElementById('top').innerHTML = '<p>No new available courses</p>'	    
	    }
        }
    });
	}
});

</script>

{% endblock %}